apiVersion: v1
kind: Pod
metadata:
  name: nginx12
  namespace: kubekart # you should create namespace with name before    # kubectl create ns kubekart
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
