# controlplane ~ ➜  echo -n "admin" | base64
#YWRtaW4=

#controlplane ~ ➜  echo -n "mysecretpass" | base64
#bXlzZWNyZXRwYXNz
# the above two command should be run before running this yaml file
# the values in the username and password were taken by running thos commands .

#controlplane ~ ➜  kubectl create -f mysecret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  username: YWRtaW4=
  password: bXlzZWNyZXRwYXNz
type: Opaque
