apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: mycontainer
      image: redis
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
              optional:
                false # same as default; "mysecret" must exist
                # and include a key named "username"
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret # this name should match with name mentioned in the mysecret.yaml file
              key: password
              optional:
                false # same as default; "mysecret" must exist
                # and include a key named "password"
  restartPolicy: Never
#  kubectl create -f readsecret.yaml
# kubectl exec --stdin --tty secret-env-pod -- /bin/bash   --> to connect with the pod
